package exception_handling;

public class ArrayException {
//	public void show() {
//		try {
//			int arr[]= {2,3};
//			for (int i=0; i<arr.length+1; i++) {
//				System.out.println(arr[i]);
//				
//			}
//			
//		}
//		catch(ArrayIndexOutOfBoundsException ae){
//			ae.printStackTrace();
//		}
//		
//	}
//
//	public static void main(String[] args) {
//		
//		ArrayException obj = new ArrayException();
//		obj.show();
//	}
//
//}
	
	
	
	public static void main(String[] args) {
		try {
			Thread.sleep(100);
		} catch (InterruptedException e) {
			
			System.out.println("Main method");
			
		}
		
	
	}
	
	}
